title: MAP-CS Grant
description: MAP-CS project website

url: "https://map-cs.org"
baseurl: ""      # keep empty for apex/custom domain

theme: jekyll-theme-primer

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
