title: MAP-CS Grant
description: MAP-CS project website
url: "https://map-cs.org"
baseurl: ""      # keep empty for apex domain

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
