title: MAP-CS Grant
description: MAP-CS project website

url: "https://map-cs.org"
baseurl: ""      # leave empty for apex/custom domain

# Use Just the Docs as a remote theme
remote_theme: just-the-docs/just-the-docs@v0.5.2

plugins:
  - jekyll-remote-theme

# Basic Just the Docs configuration
just_the_docs:
  color_scheme: light

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
