title: MAP-CS Grant
description: MAP-CS project website
url: "https://map-cs.org"
baseurl: ""      # keep empty for apex domain

#theme: minima

remote_theme: pages-themes/minimal@v0.2.0

minima:
  skin: classic
  nav_pages:
    - index.md
    - welcome.md
    - overview.md
    - nsf-sigcse-acm.md
    - supporting-material/index.md
    - process-workbook/index.md
    - other/index.md
    - contact.md

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
